Repository woowa-techcamp-2020/market-6, pull requests merged in 2020-07, with the labels that each got.

#11 Test validators
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/main.ts
  server/src/modules/validators/__TEST__/validate-id.spec.ts
  server/src/modules/validators/__TEST__/validate-password.spec.ts
  server/src/modules/validators/validate-id.ts
  server/src/modules/validators/validate-password.ts
  server/tsconfig.json
Labels: test

#13 Implement other validators
  server/src/modules/validators/__TEST__/validate-id.spec.ts
  server/src/modules/validators/__TEST__/validate-name.spec.ts
  server/src/modules/validators/__TEST__/validate-password.spec.ts
  server/src/modules/validators/validate-email.ts
  server/src/modules/validators/validate-id.ts
  server/src/modules/validators/validate-name.ts
  server/src/modules/validators/validate-password.ts
  server/src/modules/validators/validate-phone.ts
Labels: feat

#14 Setup db
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/db.ts
  server/src/main.ts
Labels: environment

#15 Feat/entity setup
  server/package-lock.json
  server/package.json
  server/src/api/index.ts
  server/src/api/sign-in.ts
  server/src/api/sign-up.ts
  server/src/app.ts
  server/src/modules/db-helper/user.ts
  server/src/modules/encryption.ts
  server/src/modules/validators/index.ts
Labels: feat

#16 Refactor/test format
  .vscode/typescript.code-snippets
  server/src/modules/validators/__TEST__/validate-email.spec.ts
  server/src/modules/validators/__TEST__/validate-id.spec.ts
  server/src/modules/validators/__TEST__/validate-name.spec.ts
  server/src/modules/validators/__TEST__/validate-password.spec.ts
  server/src/modules/validators/__TEST__/validate-phone.spec.ts
  server/src/modules/validators/validate-id.ts
  server/src/modules/validators/validate-password.ts
Labels: refactor, test

#17 Feat/store functions
  .gitignore
  server/src/db.ts
  server/src/main.ts
  server/src/modules/database/crud.ts
  server/src/modules/database/schema/user.ts
  server/src/modules/database/schema/userToken.ts
  server/src/modules/database/store.ts
  server/src/modules/db-helper/user.ts
  server/tsconfig.json
Labels: feat

#19 Feat/authentication
  .vscode/typescript.code-snippets
  server/package-lock.json
  server/package.json
  server/src/api/__TEST__/sign-in.spec.ts
  server/src/api/sign-in.ts
  server/src/modules/database/crud.ts
  server/src/modules/database/schema/user.ts
  server/src/modules/database/schema/userToken.ts
  server/src/modules/validators/__TEST__/validate-email.spec.ts
  server/src/modules/validators/__TEST__/validate-id.spec.ts
  server/src/modules/validators/__TEST__/validate-name.spec.ts
  server/src/modules/validators/__TEST__/validate-password.spec.ts
  server/src/modules/validators/__TEST__/validate-phone.spec.ts
Labels: api, backend, db

#21 Sign up test and implementation
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/api/__TEST__/sign-up.spec.ts
  server/src/api/sign-up.ts
  server/tsconfig.json
Labels: feat

#24 Feat/sign up
  server/jest.config.js
  server/src/api/__TEST__/sign-in.spec.ts
  server/src/api/__TEST__/sign-up.spec.ts
  server/src/api/sign-up.ts
  server/src/middlewares/validate-body.ts
  server/src/modules/database/crud.ts
  server/src/modules/database/schema/user.ts
Labels: feat

#28 Update README.md
  README.md
Labels: documentation

#29 Feat/error message handle
  server/package-lock.json
  server/package.json
  server/src/api/__TEST__/sign-up.spec.ts
  server/src/api/sign-in.ts
  server/src/app.ts
  server/src/errors.ts
  server/src/modules/validators/__TEST__/validate-id.spec.ts
  server/src/modules/validators/__TEST__/validate-name.spec.ts
  server/src/modules/validators/index.ts
  server/src/modules/validators/validate-user-id.ts
  server/src/views/current-user/current-user.css
  server/src/views/current-user/current-user.js
  server/src/views/current-user/current-user.pug
  server/src/views/main.pug
  server/src/views/sign-in/sign-in.css
  server/src/views/sign-in/sign-in.js
  server/src/views/sign-in/sign-in.pug
  server/src/views/sign-up/sign-up.css
  server/src/views/sign-up/sign-up.js
  server/src/views/sign-up/sign-up.pug
Labels: feat, refactor

#30 feat: setup client side
  client/package-lock.json
  client/package.json
  client/src/main.ts
  client/tsconfig.json
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
  server/package-lock.json
  server/src/app.ts
  server/src/routers/home.ts
  server/src/routers/index.ts
  server/src/routers/sign-in.ts
  server/src/routers/sign-up.ts
  server/src/views/index.pug
Labels: environment, frontend

#31 Setup client
  client/package.json
  client/src/main.ts
  server/package-lock.json
  server/package.json
  server/src/public/assets/icons/id-tag.svg
  server/src/public/assets/icons/key.svg
  server/src/public/styles/globalstyle.css
  server/src/public/styles/sign-up.css
  server/src/routers/index.ts
  server/src/routers/sign-up.ts
  server/src/views-html/sign-up.html
Labels: environment, frontend

#33 Sign up page
  client/src/main.ts
  server/src/public/assets/icons/field.svg
  server/src/public/assets/icons/home.svg
  server/src/public/assets/icons/mail.svg
  server/src/public/assets/icons/person.svg
  server/src/public/assets/icons/phone.svg
  server/src/public/assets/images/logo-ceo.svg
  server/src/public/favicon.ico
  server/src/public/styles/common/globalstyle.css
  server/src/public/styles/common/input.css
  server/src/public/styles/sign-up.css
  server/src/views-html/sign-up.html
Labels: feat, frontend

#32 Feat/fe pug
  server/src/api/current-user.ts
  server/src/api/sign-in.ts
  server/src/api/sign-up.ts
  server/src/middlewares/current-user.ts
  server/src/modules/validators/validate-id.ts
  server/src/public/assets/icons/check.svg
  server/src/public/styles/common/globalstyle.css
  server/src/public/styles/sign-in.css
  server/src/routers/index.ts
  server/src/routers/sign-in.ts
  server/src/views-html/sign-in.html
  server/src/views/current-user/current-user.css
  server/src/views/current-user/current-user.pug
  server/src/views/sign-in/sign-in.pug
Labels: feat, frontend

#34 Feat/sign in dom handle
  client/src/main.ts
  client/src/sign-in.ts
  client/src/sign-up.ts
  client/webpack.common.js
  server/src/public/styles/common/input.css
  server/src/views-html/sign-in.html
  server/src/views/current-user/current-user.pug
Labels: frontend

#35 Feat/sign in dom handle
  client/src/main.ts
  client/src/sign-in.ts
  server/src/api/sign-in.ts
  server/src/api/sign-up.ts
  server/src/errors.ts
  server/src/types.ts
  server/src/views-html/sign-in.html
Labels: feat, frontend

#36 Feat/fe/sign up
  client/src/sign-up.ts
  server/src/api/index.ts
  server/src/api/validate-user-id.ts
  server/src/app.ts
  server/src/modules/validators/validate-email.ts
  server/src/modules/validators/validate-name.ts
  server/src/modules/validators/validate-password.ts
  server/src/modules/validators/validate-phone.ts
  server/src/modules/validators/validate-user-id.ts
  server/src/public/styles/common/input.css
  server/src/views-html/sign-up.html
Labels: feat, frontend

#37 Feat/sign in dom handle
  client/src/main.ts
  client/src/sign-in.ts
  client/src/sign-up.ts
  server/src/api/sign-in.ts
  server/src/api/sign-up.ts
  server/src/middlewares/validate-body.ts
  server/src/modules/database/schema/user.ts
  server/src/views-html/sign-up.html
Labels: api, feat, frontend

#40 Feat/fe/sign up
  client/package.json
  client/src/modules/set-input-wrapper.ts
  client/src/sign-up/essential-part.ts
  client/src/sign-up/index.ts
  client/src/styles/spring.styl
  client/webpack.common.js
  server/src/public/fonts/Icons/Icons-Regular.eot
  server/src/public/fonts/Icons/Icons-Regular.ttf
  server/src/public/fonts/Icons/Icons-Regular.woff
  server/src/public/fonts/Icons/Icons-Regular.woff2
  server/src/public/fonts/Inter/Inter-Bold.woff
  server/src/public/fonts/Inter/Inter-Bold.woff2
  server/src/public/fonts/Inter/Inter-ExtraBold.woff
  server/src/public/fonts/Inter/Inter-ExtraBold.woff2
  server/src/public/fonts/Inter/Inter-Medium.woff
  server/src/public/fonts/Inter/Inter-Medium.woff2
  server/src/public/fonts/Inter/Inter-Regular.woff
  server/src/public/fonts/Inter/Inter-Regular.woff2
  server/src/public/fonts/Inter/Inter-SemiBold.woff
  server/src/public/fonts/Inter/Inter-SemiBold.woff2
  server/src/public/fonts/NotoSansKR/NotoSansKR-Black.woff
  server/src/public/fonts/NotoSansKR/NotoSansKR-Black.woff2
  server/src/public/fonts/NotoSansKR/NotoSansKR-Bold.woff
  server/src/public/fonts/NotoSansKR/NotoSansKR-Bold.woff2
  server/src/public/fonts/NotoSansKR/NotoSansKR-DemiLight.woff
  server/src/public/fonts/NotoSansKR/NotoSansKR-DemiLight.woff2
  server/src/public/fonts/NotoSansKR/NotoSansKR-Light.woff
  server/src/public/fonts/NotoSansKR/NotoSansKR-Light.woff2
  server/src/public/fonts/NotoSansKR/NotoSansKR-Medium.woff
  server/src/public/fonts/NotoSansKR/NotoSansKR-Medium.woff2
  server/src/public/fonts/NotoSansKR/NotoSansKR-Regular.woff
  server/src/public/fonts/NotoSansKR/NotoSansKR-Regular.woff2
  server/src/public/fonts/NotoSansKR/NotoSansKR-Thin.woff
  server/src/public/fonts/NotoSansKR/NotoSansKR-Thin.woff2
  server/src/public/styles/common/fonts.css
  server/src/public/styles/common/globalstyle.css
  server/src/public/styles/common/input.css
  server/src/public/styles/common/spring.css
  server/src/public/styles/sign-up.css
  server/src/views-html/sign-up.html
Labels: feat, frontend

#41 Feat/fe/timer
  client/src/main.ts
  client/src/sign-up.ts
  client/src/sign-up/additional-part.ts
  client/src/sign-up/essential-part.ts
  client/src/sign-up/index.ts
  server/src/public/styles/sign-up.css
  server/src/views-html/sign-up.html
Labels: feat, frontend

#42 feat/fe/sign-up
  client/src/modules/set-input-wrapper.ts
  client/src/sign-up.ts
  client/src/sign-up/essential-part.ts
  client/src/sign-up/index.ts
  client/src/sign-up/optional-part.ts
  client/src/sign-up/policy.ts
  client/src/sign-up/submit.ts
  client/tsconfig.json
  server/src/api/sign-up.ts
  server/src/modules/database/schema/user.ts
  server/src/public/styles/common/globalstyle.css
  server/src/public/styles/common/input.css
  server/src/public/styles/sign-up.css
  server/src/views-html/sign-up.html
Labels: feat

#46 Feat/auth session
  client/src/main.ts
  client/src/sign-up/essential-part.ts
  server/package-lock.json
  server/package.json
  server/src/api/current-user.ts
  server/src/api/index.ts
  server/src/api/sign-in.ts
  server/src/api/sign-out.ts
  server/src/api/sign-up.ts
  server/src/api/welcome.ts
  server/src/app.ts
  server/src/views-html/sign-in.html
Labels: api, backend

#47 Feat/welcome page
  client/src/sign-in.ts
  client/src/sign-up/essential-part.ts
  server/package-lock.json
  server/package.json
  server/src/api/sign-in.ts
  server/src/api/sign-out.ts
  server/src/api/welcome.ts
  server/src/middlewares/validate-body.ts
  server/src/public/styles/common/button.css
  server/src/public/styles/common/globalstyle.css
  server/src/public/styles/common/input.css
  server/src/public/styles/sign-in.css
  server/src/public/styles/sign-up.css
  server/src/routers/home.ts
  server/src/routers/sign-in.ts
  server/src/routers/sign-up.ts
  server/src/views-html/sign-in.html
  server/src/views-html/sign-up.html
  server/src/views/current-user/current-user.css
  server/src/views/current-user/current-user.js
  server/src/views/welcome/welcome.css
  server/src/views/welcome/welcome.pug
Labels: enhancement, feat, frontend

#50 Terms of service
  client/src/sign-up/index.ts
  client/src/sign-up/term-content/index.ts
  client/src/sign-up/term.ts
  client/src/styles/spring.styl
  server/src/api/welcome.ts
  server/src/public/assets/images/rider.png
  server/src/public/styles/common/spring.css
  server/src/public/styles/sign-up.css
  server/src/views-html/sign-up.html
Labels: feat

#52 fix: resolve #51
  client/src/styles/spring.styl
  server/src/public/styles/common/input.css
  server/src/public/styles/common/spring.css
  server/src/public/styles/sign-in.css
  server/src/public/styles/sign-up.css
Labels: fix
